### ISSUE TITLE
Message Receiving Object should be flushed before getting new message

### ISSUE THREAD

**Issue by OnTitansShoulder** [MatthewBregg/TigerIsland#37]
Hello server team, when my team is testing the tournament, we noticed one issue:
When one of the players is timed out (took more than allowed time to complete the move), the server sent out the player forfeited message but never flush the input stream. This will cause the late message from the client to stay in the input stream and be read on the next move prompt. Please see the attached scenario: 
Server console messages:
![image](https://cloud.githubusercontent.com/assets/16210646/24886045/f437b980-1e1f-11e7-986c-5d85f8612434.png)
Client console messages:
![image](https://cloud.githubusercontent.com/assets/16210646/24886108/601264fc-1e20-11e7-82fa-c71190515b47.png)

Thanks.

**Comment by MatthewBregg** [comment]
We believe this to be fixed now, let us know if otherwise.
