### ISSUE TITLE
Timing Out

### ISSUE THREAD

**Issue by 24vincenti** [MatthewBregg/TigerIsland#40]
It seems that if player A times out in a game against player B, B is getting the timeout message and forfeiting the game. It ends with both players forfeiting going 1W - 1L. Im not sure if this is on the server end but seems weird.

LINK:  https://pastebin.com/zFdhgPUL

-Vincent

**Comment by MatthewBregg** [comment]
Looks like it was caused by us prematurely clearing the buffer, in response to the last issue. 

I think we have it now so that is clears non prematurely, so won't have your message removed, and garbage won't stay in input queue and muck things up.
