### ISSUE TITLE
Server still rejecting seemingly legal nukes with NukeHexesOfDifferentTilesRuleException

### ISSUE THREAD

**Issue by wylieallen** [MatthewBregg/TigerIsland#42]
Just ran a quick 1v1 tournament with the (then) latest master, log file here: https://pastebin.com/WwpyGBj8

Game A screenshot: http://i.imgur.com/3wEd0pA.png

Game B screenshot: http://i.imgur.com/Lr4pLDw.png

The hex highlighted in pink in either screenshot is the target volcano of the moves that triggered the forfeit. Both nukes should be legal according to our client's representation of the game.

**Comment by thephil16** [comment]
What commit number were you running?

**Comment by wylieallen** [comment]
This tournament was run on b5576cfaec9467bf2103c2e40e5d6c0098fa179a:

https://github.com/MatthewBregg/TigerIsland/commit/b5576cfaec9467bf2103c2e40e5d6c0098fa179a

**Comment by wylieallen** [comment]
Here's another tournament with the same issue run on https://github.com/MatthewBregg/TigerIsland/commit/0497d1b2b2ce31224998d8122509518821d7c0a3:

Log: https://pastebin.com/haDGva2A

Game A before forfeit: http://i.imgur.com/9XsXSxD.png

Game B before forfeit: http://i.imgur.com/m7NQMvC.png

**Comment by r3h4** [comment]
I've looked at this and run it using the exact messages from the logs you have provided. I cannot replicate it. Will return to it after fixing some other things

**Comment by wylieallen** [comment]
I deleted and re-downloaded the server and it's working now, this issue can probably be closed
