### ISSUE TITLE
Legal Totoro build called illegal

### ISSUE THREAD

**Issue by Megagator** [MatthewBregg/TigerIsland#44]
```
GAME B MOVE 0 PLAYER 2 PLACED GRASS+GRASS AT -2 2 0 3 FOUNDED SETTLEMENT AT -1 0 1
GAME B MOVE 0 PLAYER 1 PLACED ROCK+ROCK AT 0 0 0 6 FOUNDED SETTLEMENT AT 0 -1 1
GAME B MOVE 1 PLAYER 2 PLACED ROCK+JUNGLE AT 1 -3 2 6 FOUNDED SETTLEMENT AT -2 1 1
GAME B MOVE 1 PLAYER 1 PLACED GRASS+GRASS AT 0 -3 3 3 FOUNDED SETTLEMENT AT 1 -2 1
GAME B MOVE 2 PLAYER 2 PLACED LAKE+LAKE AT 0 -3 3 2 EXPANDED SETTLEMENT AT -2 1 1 ROCK
GAME B MOVE 2 PLAYER 1 PLACED GRASS+GRASS AT 3 0 -3 4 FOUNDED SETTLEMENT AT 0 -2 2
GAME B MOVE 3 PLAYER 2 PLACED GRASS+LAKE AT -2 -2 4 2 FOUNDED SETTLEMENT AT 1 0 -1
GAME B MOVE 3 PLAYER 1 PLACED LAKE+ROCK AT 3 1 -4 6 FOUNDED SETTLEMENT AT -1 -2 3
GAME B MOVE 4 PLAYER 2 PLACED LAKE+GRASS AT 3 -3 0 6 BUILT TOTORO SANCTUARY AT 2 0 -2
GAME B MOVE 4 PLAYER 1 PLACED ROCK+LAKE AT 5 -4 -1 4 FOUNDED SETTLEMENT AT -1 -3 4
GAME B MOVE 5 PLAYER 2 PLACED JUNGLE+ROCK AT 6 -7 1 6 FOUNDED SETTLEMENT AT 5 -5 0
GAME B MOVE 5 PLAYER 1 PLACED GRASS+JUNGLE AT 4 -7 3 2 BUILT TOTORO SANCTUARY AT 0 -4 4
GAME B MOVE 6 PLAYER 2 PLACED GRASS+ROCK AT 6 -7 1 5 FOUNDED SETTLEMENT AT 4 -4 0
GAME B MOVE 6 PLAYER 1 PLACED ROCK+ROCK AT 3 3 -6 1 FOUNDED SETTLEMENT AT 2 -2 0
GAME B MOVE 7 PLAYER 2 PLACED JUNGLE+GRASS AT -3 -3 6 2 FOUNDED SETTLEMENT AT 6 -6 0
Sending:  GAME B MOVE 7 PLACE GRASS+JUNGLE AT -2 -2 4 3 BUILD TOTORO SANCTUARY AT -1 -3 4
GAME B MOVE 7 PLAYER 1 FORFEITED: ILLEGAL BUILD
```
State of the board after player 1's totoro was placed:
![screen shot 2017-04-12 at 12 36 55 pm](https://cloud.githubusercontent.com/assets/6308213/24968912/dbd1267a-1f7c-11e7-8750-f7fc5ca1d930.png)

**Comment by SlightlyUnorthodox** [comment]
I'll second this issue. We've been running up against valid Totoro builds being parsed as illegal. Here's a complete set of logs for server and client from one of these incidents.

https://drive.google.com/drive/folders/0B6B24hZoE7XwWTAxMmhFYUxWV2M?usp=sharing

**Comment by MatthewBregg** [comment]
Should be fixed, let me know elsewise

**Comment by JohnZoldos** [comment]
This is still a bug. In this log you can see at challenge 0 in game B, Client 2 makes a totoro placement at a valid location for Move 13 (in between a settlement capable of accepting a totoro and a settlement not capable of accepting a totoro) but the move is rejected.

It's at line 613 here: https://pastebin.com/xK7re9Ru

**Comment by MatthewBregg** [comment]
Can you check if this is still happening with the latest build?

**Comment by JohnZoldos** [comment]
So far I haven't seen it but it seems like there's a new issue where it keeps saying our client is making illegal tile placements which is doubtful. I'll make sure the placements are legal and make a new issue if so.

**Comment by r3h4** [comment]
I replicated Game B where you had the totoro bug  from https://pastebin.com/xK7re9Ru

No bug in our game. Log: https://pastebin.com/xK7re9Ru line 275 shows valid placement

**Comment by MatthewBregg** [comment]
Reopen if it happens again
