### ISSUE TITLE
Forfeiting instead of winning after placing all of two kinds of pieces

### ISSUE THREAD

**Issue by linaresm** [MatthewBregg/TigerIsland#45]
When testing we placed all my tigers and then expanded away all our meeples. We sent the game unable to build and it returned that we lost the match, this happens every time we use all of two kinds of pieces.
[https://gyazo.com/752d285ff87cfa848faf69c41d23ce18](url)

**Comment by r3h4** [comment]
This is the log we made with a similar scenario. The bug did not appear for us and the message was correct. We only played one game so ignore Game B. We also played with modified totoro and villager counts to reduce the amount of moves needed. Same thing though. IN the future, please post your log -- not a screen shot


/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java -Didea.launcher.port=7544 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/tools.jar:/Users/josh/Documents/gitRepos/CEN3031/TigerIsland/buildOut/production/TigerIsland:/Users/josh/.m2/repository/info/cukes/cucumber-java8/1.2.5/cucumber-java8-1.2.5.jar:/Users/josh/.m2/repository/info/cukes/cucumber-java/1.2.5/cucumber-java-1.2.5.jar:/Users/josh/.m2/repository/info/cukes/cucumber-core/1.2.5/cucumber-core-1.2.5.jar:/Users/josh/.m2/repository/info/cukes/cucumber-html/0.2.3/cucumber-html-0.2.3.jar:/Users/josh/.m2/repository/info/cukes/cucumber-jvm-deps/1.0.5/cucumber-jvm-deps-1.0.5.jar:/Users/josh/.m2/repository/info/cukes/gherkin/2.12.2/gherkin-2.12.2.jar:/Users/josh/Downloads/sqlite-jdbc-3.16.1.jar:/Users/josh/Downloads/mockito-all-1.10.19.jar:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain tigerislandserver.RunTournamentServer 3 heygang pass.txt 20 6969 123456789
Server socket will close in: 20 seconds
SENDING MESSAGE TO 1: "WELCOME TO ANOTHER EDITION OF THUNDERDOME!"
15 seconds remaining
CLIENT: ENTER THUNDERDOME heygang
SENDING MESSAGE TO 1: "TWO SHALL ENTER, ONE SHALL LEAVE"
CLIENT 1:I AM TEAM_B PASS_B
SENDING MESSAGE TO 1: "WAIT FOR THE TOURNAMENT TO BEGIN 1"
SENDING MESSAGE TO 2: "WELCOME TO ANOTHER EDITION OF THUNDERDOME!"
10 seconds remaining
CLIENT: ENTER THUNDERDOME heygang
SENDING MESSAGE TO 2: "TWO SHALL ENTER, ONE SHALL LEAVE"
CLIENT 2:I AM TEAM_A PASS_A
SENDING MESSAGE TO 2: "WAIT FOR THE TOURNAMENT TO BEGIN 2"
5 seconds remaining
0 seconds remaining
Server socket closed!
SENDING MESSAGE TO 1: "NEW CHALLENGE 0 YOU WILL PLAY 1 MATCH"
SENDING MESSAGE TO 2: "NEW CHALLENGE 0 YOU WILL PLAY 1 MATCH"
!!!!!!!THIS SHOULD NOT APPEAR IN YOUR CONSOLE, IF IT DOES, FIND OUT WHY AND REMOVE THE CALL TO THIS CONSTRUCTOR
SENDING MESSAGE TO 1: "BEGIN ROUND 1 OF 1"
SENDING MESSAGE TO 2: "BEGIN ROUND 1 OF 1"
SENDING MESSAGE TO 1: "NEW MATCH BEGINNING NOW YOUR OPPONENT IS PLAYER 2"
SENDING MESSAGE TO 2: "NEW MATCH BEGINNING NOW YOUR OPPONENT IS PLAYER 1"
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 0 ::p1 1 p2 2
SENDING MESSAGE TO 1: "MAKE YOUR MOVE IN GAME A WITHIN 1.5 SECONDS: MOVE 0 PLACE LAKE+LAKE"
Logger: Game Id: B Challenge Id: 0 Match ID : 0 Turn Number 0 ::p1 2 p2 1
SENDING MESSAGE TO 2: "MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 0 PLACE LAKE+LAKE"
SENDING MESSAGE TO 2: "GAME B MOVE 0 PLAYER 2 FORFEITED: TIMEOUT"
SENDING MESSAGE TO 1: "GAME B MOVE 0 PLAYER 2 FORFEITED: TIMEOUT"
Logger: Game Id: B Challenge Id: 0 Match ID : 0 Turn Number 0 :: Turn has ended
CLIENT 1: GAME A MOVE 0 PLACE LAKE+LAKE AT 2 -2 0 6 FOUND SETTLEMENT AT 1 -1 0
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 0 :: placed a tile in location (2, -2, 0) with the follow terrain tigerisland.tile.Tile@79db0fae at orientation Southwest
Logger: Game Id: B Challenge Id: 0 Match ID : 0 Turn Number 1 ::GAME B OVER PLAYER 2 FORFEITED PLAYER 1 WIN Winner 2 Loser 1
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 0 ::Tile placement (2, -2, 0) true , tigerisland.tile.Tile@79db0fae SIZE OF BOARD IS 8
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 0 ::Player TEAM_Bfounded a settlement in location (1, -1, 0)
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 0 ::FoundSettlement (1, -1, 0) true 
SENDING MESSAGE TO 1: "GAME A MOVE 0 PLAYER 1 PLACED LAKE+LAKE AT 2 -2 0 6 FOUNDED SETTLEMENT AT 1 -1 0"
SENDING MESSAGE TO 2: "GAME A MOVE 0 PLAYER 1 PLACED LAKE+LAKE AT 2 -2 0 6 FOUNDED SETTLEMENT AT 1 -1 0"
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 0 :: Turn has ended
SENDING MESSAGE TO 2: "MAKE YOUR MOVE IN GAME A WITHIN 1.5 SECONDS: MOVE 0 PLACE LAKE+LAKE"
CLIENT 2: GAME A MOVE 0 PLACE LAKE+LAKE AT 3 -3 0 1 FOUND SETTLEMENT AT -1 0 1
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 1 :: placed a tile in location (3, -3, 0) with the follow terrain tigerisland.tile.Tile@3c28b9 at orientation West
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 1 ::Tile placement (3, -3, 0) true , tigerisland.tile.Tile@3c28b9 SIZE OF BOARD IS 11
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 1 ::Player TEAM_Afounded a settlement in location (-1, 0, 1)
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 1 ::FoundSettlement (-1, 0, 1) true 
SENDING MESSAGE TO 1: "GAME A MOVE 0 PLAYER 2 PLACED LAKE+LAKE AT 3 -3 0 1 FOUNDED SETTLEMENT AT -1 0 1"
SENDING MESSAGE TO 2: "GAME A MOVE 0 PLAYER 2 PLACED LAKE+LAKE AT 3 -3 0 1 FOUNDED SETTLEMENT AT -1 0 1"
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 1 :: Turn has ended
SENDING MESSAGE TO 1: "MAKE YOUR MOVE IN GAME A WITHIN 1.5 SECONDS: MOVE 1 PLACE LAKE+LAKE"
CLIENT 1: GAME A MOVE 1 PLACE LAKE+LAKE AT 1 -2 1 4 EXPAND SETTLEMENT AT 1 -1 0 LAKE
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 2 :: placed a tile in location (1, -2, 1) with the follow terrain tigerisland.tile.Tile@76b5d40e at orientation East
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 2 ::Tile placement (1, -2, 1) true , tigerisland.tile.Tile@76b5d40e SIZE OF BOARD IS 14
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 2 ::Player TEAM_B expanded settlement at (1, -1, 0) to cover terrain of LAKE
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 2 ::Expand Settlement true 
SENDING MESSAGE TO 1: "GAME A MOVE 1 PLAYER 1 PLACED LAKE+LAKE AT 1 -2 1 4 EXPANDED SETTLEMENT AT 1 -1 0 LAKE"
SENDING MESSAGE TO 2: "GAME A MOVE 1 PLAYER 1 PLACED LAKE+LAKE AT 1 -2 1 4 EXPANDED SETTLEMENT AT 1 -1 0 LAKE"
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 2 :: Turn has ended
SENDING MESSAGE TO 2: "MAKE YOUR MOVE IN GAME A WITHIN 1.5 SECONDS: MOVE 1 PLACE LAKE+LAKE"
CLIENT 2: GAME A MOVE 1 PLACE LAKE+LAKE AT -1 2 -1 1 FOUND SETTLEMENT AT -1 3 -2
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 3 :: placed a tile in location (-1, 2, -1) with the follow terrain tigerisland.tile.Tile@2c165e55 at orientation West
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 3 ::Tile placement (-1, 2, -1) true , tigerisland.tile.Tile@2c165e55 SIZE OF BOARD IS 17
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 3 ::Player TEAM_Afounded a settlement in location (-1, 3, -2)
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 3 ::FoundSettlement (-1, 3, -2) true 
SENDING MESSAGE TO 1: "GAME A MOVE 1 PLAYER 2 PLACED LAKE+LAKE AT -1 2 -1 1 FOUNDED SETTLEMENT AT -1 3 -2"
SENDING MESSAGE TO 2: "GAME A MOVE 1 PLAYER 2 PLACED LAKE+LAKE AT -1 2 -1 1 FOUNDED SETTLEMENT AT -1 3 -2"
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 3 :: Turn has ended
SENDING MESSAGE TO 1: "MAKE YOUR MOVE IN GAME A WITHIN 1.5 SECONDS: MOVE 2 PLACE LAKE+LAKE"
CLIENT 1: GAME A MOVE 2 PLACE LAKE+LAKE AT -2 1 1 4 BUILD TOTORO SANCTUARY AT 0 1 -1
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 4 :: placed a tile in location (-2, 1, 1) with the follow terrain tigerisland.tile.Tile@1f1a854c at orientation East
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 4 ::Tile placement (-2, 1, 1) true , tigerisland.tile.Tile@1f1a854c SIZE OF BOARD IS 20
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 4 ::Player TEAM_Bplaced a totoro in location (0, 1, -1)
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 4 ::Totoroplacement (0, 1, -1) true 
SENDING MESSAGE TO 1: "GAME A MOVE 2 PLAYER 1 PLACED LAKE+LAKE AT -2 1 1 4 BUILT TOTORO SANCTUARY AT 0 1 -1"
SENDING MESSAGE TO 2: "GAME A MOVE 2 PLAYER 1 PLACED LAKE+LAKE AT -2 1 1 4 BUILT TOTORO SANCTUARY AT 0 1 -1"
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 4 :: Turn has ended
Logger: Game Id: A Challenge Id: 0 Match ID : 0 Turn Number 5 ::GAME A OVER PLAYER 1 205 PLAYER 2 2 Winner 1 Loser 2
SENDING MESSAGE TO 1: "GAME A OVER PLAYER 1 205 PLAYER 2 2"
SENDING MESSAGE TO 2: "GAME A OVER PLAYER 1 205 PLAYER 2 2"
SENDING MESSAGE TO 2: "GAME B OVER PLAYER 2 FORFEITED PLAYER 1 WIN"
SENDING MESSAGE TO 1: "GAME B OVER PLAYER 2 FORFEITED PLAYER 1 WIN"
SENDING MESSAGE TO 1: "END OF ROUND 1 OF 1"
SENDING MESSAGE TO 2: "END OF ROUND 1 OF 1"
SENDING MESSAGE TO 1: "WAIT FOR THE NEXT CHALLENGE TO BEGIN"
!!!!!!!THIS SHOULD NOT APPEAR IN YOUR CONSOLE, IF IT DOES, FIND OUT WHY AND REMOVE THE CALL TO THIS CONSTRUCTOR
SENDING MESSAGE TO 2: "WAIT FOR THE NEXT CHALLENGE TO BEGIN"
SENDING MESSAGE TO 1: "NEW CHALLENGE 1 YOU WILL PLAY 1 MATCH"
SENDING MESSAGE TO 2: "NEW CHALLENGE 1 YOU WILL PLAY 1 MATCH"
SENDING MESSAGE TO 1: "BEGIN ROUND 1 OF 1"
SENDING MESSAGE TO 2: "BEGIN ROUND 1 OF 1"
SENDING MESSAGE TO 1: "NEW MATCH BEGINNING NOW YOUR OPPONENT IS PLAYER 2"
SENDING MESSAGE TO 2: "NEW MATCH BEGINNING NOW YOUR OPPONENT IS PLAYER 1"
Logger: Game Id: A Challenge Id: 1 Match ID : 1 Turn Number 0 ::p1 1 p2 2
SENDING MESSAGE TO 1: "MAKE YOUR MOVE IN GAME A WITHIN 1.5 SECONDS: MOVE 0 PLACE LAKE+LAKE"
Logger: Game Id: B Challenge Id: 1 Match ID : 1 Turn Number 0 ::p1 2 p2 1
SENDING MESSAGE TO 2: "MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 0 PLACE LAKE+LAKE"
SENDING MESSAGE TO 1: "GAME A MOVE 0 PLAYER 1 FORFEITED: TIMEOUT"
SENDING MESSAGE TO 2: "GAME A MOVE 0 PLAYER 1 FORFEITED: TIMEOUT"
Logger: Game Id: A Challenge Id: 1 Match ID : 1 Turn Number 0 :: Turn has ended
Logger: Game Id: A Challenge Id: 1 Match ID : 1 Turn Number 1 ::GAME A OVER PLAYER 1 FORFEITED PLAYER 2 WIN Winner 1 Loser 2
SENDING MESSAGE TO 2: "GAME B MOVE 0 PLAYER 2 FORFEITED: TIMEOUT"
SENDING MESSAGE TO 1: "GAME B MOVE 0 PLAYER 2 FORFEITED: TIMEOUT"
Logger: Game Id: B Challenge Id: 1 Match ID : 1 Turn Number 0 :: Turn has ended
Logger: Game Id: B Challenge Id: 1 Match ID : 1 Turn Number 1 ::GAME B OVER PLAYER 2 FORFEITED PLAYER 1 WIN Winner 2 Loser 1
SENDING MESSAGE TO 1: "GAME A OVER PLAYER 1 FORFEITED PLAYER 2 WIN"
SENDING MESSAGE TO 2: "GAME A OVER PLAYER 1 FORFEITED PLAYER 2 WIN"
SENDING MESSAGE TO 2: "GAME B OVER PLAYER 2 FORFEITED PLAYER 1 WIN"
SENDING MESSAGE TO 1: "GAME B OVER PLAYER 2 FORFEITED PLAYER 1 WIN"
SENDING MESSAGE TO 1: "END OF ROUND 1 OF 1"
SENDING MESSAGE TO 2: "END OF ROUND 1 OF 1"
!!!!!!!THIS SHOULD NOT APPEAR IN YOUR CONSOLE, IF IT DOES, FIND OUT WHY AND REMOVE THE CALL TO THIS CONSTRUCTOR
SENDING MESSAGE TO 1: "WAIT FOR THE NEXT CHALLENGE TO BEGIN"
SENDING MESSAGE TO 2: "WAIT FOR THE NEXT CHALLENGE TO BEGIN"
SENDING MESSAGE TO 1: "NEW CHALLENGE 2 YOU WILL PLAY 1 MATCH"
SENDING MESSAGE TO 2: "NEW CHALLENGE 2 YOU WILL PLAY 1 MATCH"
SENDING MESSAGE TO 1: "BEGIN ROUND 1 OF 1"
SENDING MESSAGE TO 2: "BEGIN ROUND 1 OF 1"
SENDING MESSAGE TO 1: "NEW MATCH BEGINNING NOW YOUR OPPONENT IS PLAYER 2"
SENDING MESSAGE TO 2: "NEW MATCH BEGINNING NOW YOUR OPPONENT IS PLAYER 1"
Logger: Game Id: B Challenge Id: 2 Match ID : 2 Turn Number 0 ::p1 2 p2 1
SENDING MESSAGE TO 2: "MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 0 PLACE LAKE+LAKE"
Logger: Game Id: A Challenge Id: 2 Match ID : 2 Turn Number 0 ::p1 1 p2 2
SENDING MESSAGE TO 1: "MAKE YOUR MOVE IN GAME A WITHIN 1.5 SECONDS: MOVE 0 PLACE LAKE+LAKE"
SENDING MESSAGE TO 1: "GAME A MOVE 0 PLAYER 1 FORFEITED: TIMEOUT"
SENDING MESSAGE TO 2: "GAME B MOVE 0 PLAYER 2 FORFEITED: TIMEOUT"
SENDING MESSAGE TO 1: "GAME B MOVE 0 PLAYER 2 FORFEITED: TIMEOUT"
Logger: Game Id: B Challenge Id: 2 Match ID : 2 Turn Number 0 :: Turn has ended
SENDING MESSAGE TO 2: "GAME A MOVE 0 PLAYER 1 FORFEITED: TIMEOUT"
Logger: Game Id: A Challenge Id: 2 Match ID : 2 Turn Number 0 :: Turn has ended
Logger: Game Id: B Challenge Id: 2 Match ID : 2 Turn Number 1 ::GAME B OVER PLAYER 2 FORFEITED PLAYER 1 WIN Winner 2 Loser 1
Logger: Game Id: A Challenge Id: 2 Match ID : 2 Turn Number 1 ::GAME A OVER PLAYER 1 FORFEITED PLAYER 2 WIN Winner 1 Loser 2
SENDING MESSAGE TO 1: "GAME A OVER PLAYER 1 FORFEITED PLAYER 2 WIN"
SENDING MESSAGE TO 2: "GAME A OVER PLAYER 1 FORFEITED PLAYER 2 WIN"
SENDING MESSAGE TO 2: "GAME B OVER PLAYER 2 FORFEITED PLAYER 1 WIN"
SENDING MESSAGE TO 1: "GAME B OVER PLAYER 2 FORFEITED PLAYER 1 WIN"
SENDING MESSAGE TO 1: "END OF ROUND 1 OF 1"
SENDING MESSAGE TO 2: "END OF ROUND 1 OF 1"
SENDING MESSAGE TO 1: "END OF CHALLENGES"
SENDING MESSAGE TO 2: "END OF CHALLENGES"

Process finished with exit code 0

**Comment by MatthewBregg** [comment]
Reopen this if you find it happens again, and include a log.
