### ISSUE TITLE
Server sends null messages after a player attempts to play a Totoro on an empty Hex

### ISSUE THREAD

**Issue by jlahman** [MatthewBregg/TigerIsland#47]
Placing a totoro on a hex location that hasn't been made yet will cause an unhandled exception to occur, closing the thread on that game, and causing the server to make both clients make moves in the other game at the same time, which will eventually lead to a time out, illegal build, or illegal play.

Relevant line at 169 & 170
[buildtotoroexception_server_log.txt](https://github.com/MatthewBregg/TigerIsland/files/918405/buildtotoroexception_server_log.txt)

**Comment by r3h4** [comment]
Should be fixed

**Comment by r3h4** [comment]
Still has the null pointer issue actually

**Comment by r3h4** [comment]
Now it's fixed
