### ISSUE TITLE
Totoro Placement Still Buggy

### ISSUE THREAD

**Issue by JohnZoldos** [MatthewBregg/TigerIsland#50]
I apologize if this is redundant since I already posted this comment on the closed issue thread about totoro placements between settlements not working but I just wanted to make sure its getting some attention. Here's the comment:

"This is still a bug. In this log you can see at challenge 0 in game B, Client 2 makes a totoro placement at a valid location for Move 13 (in between a settlement capable of accepting a totoro and a settlement not capable of accepting a totoro) but the move is rejected.

It's at line 613 here: https://pastebin.com/xK7re9Ru"

**Comment by MatthewBregg** [comment]
Thank you for the information, this is probably the same bug as the tiger bug, which are currently working on, but it is nice to know both are still broken.

Also, in the future, you should be able to reopen an issue, which is preferable.

**Comment by MatthewBregg** [comment]
Closing and moving back to original issue as it has more info
